name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  APIKEY: 564F181A-F0FC-114A-A55D-3C1DCD45F3767AF3848F-AB29-4EBF-9594-F91E6A75E015

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo fmt --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo clippy --all-targets --all-features -- -D warnings

  doc:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: RUSTDOCFLAGS="-Dwarnings" cargo doc --no-deps --all-features

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo test --all-features

